CXX=g++
MCXX=mipsel-linux-g++

SRCS=TimerFunc.cpp main.cpp
OBJS=timer.o

CFLAG=-o 
CFLAG3=-g 
PROGRAM=timer

all:
	$(CXX) $(CFLAG3) $(SRCS) $(CFLAG) $(PROGRAM)
M:
	$(MCXX) $(CFLAG3) $(SRCS) $(CFLAG) $(PROGRAM)
clean:
	rm $(PROGRAM) *.o -f

