all:
	g++ -g main.cpp -o watchdog
	g++ -g feed.cpp -o feeddog
	cp watchdog  /mnt/DVD3
	cp feeddog  /mnt/DVD3
M:
	mipsel-linux-g++ -g main.cpp -o watchdog
	mipsel-linux-g++ -g feed.cpp -o feeddog
	cp watchdog  /mnt/DVD3
	cp feeddog  /mnt/DVD3
