CXX=g++
MCXX=mipsel-linux-g++

SRCS=timer.cpp 
OBJS=timer.o

CFLAG=-o 
CFLAG3=-g 
PROGRAM=timer

M:
	$(MCXX) $(CFLAG3) $(SRCS) $(CFLAG) $(PROGRAM)
all:
	$(CXX) $(CFLAG3) $(SRCS) $(CFLAG) $(PROGRAM)
clean:
	rm $(PROGRAM) *.o -f

