all:
	g++ -g watchdog.cpp -o watchdog -lpthread
	g++ -g feed.cpp -o feeddog
	g++ -g serverM.cpp -o serverM
#	cp watchdog  /mnt/DVD3
#	cp feeddog  /mnt/DVD3
M:
	mipsel-linux-g++ -g watchdog.cpp -o watchdog -lpthread
	mipsel-linux-g++ -g feed.cpp -o feeddog
	cp watchdog  /mnt/DVD3
	cp feeddog  /mnt/DVD3
